- lib/constant.dart
- pubspec.lock
This PR contains several changes in order to add new microservice's status indicator to the status-page.
- Added several new microservices to status page
This changes are needed in order to update the list of indicators
- Tested in local environment
> [PAGOPA-1022] Adding missing microservice status indicators

- lib/constant.dart
This PR contains several changes made in order to expose Authorizer for Status Page service. 
- Update status page, adding Authorizer 
These updates is made in order to add a new state on Status page for Authorizer
- Tested in local environment
> [PAGOPA-1073] feat: Exposing /info API for Status Page

- lib/constant.dart
This PR contains several new status indicator for new service.
- Added status indicator for biz-event-datastore services
- Added status indicator for gpd-reporting services
- Added status indicator for canone-unico service
These changes are required in order to add new service status indicators.
- Tested in local environment
> [PAGOPA-1074] feat: added new services

- lib/constant.dart
> chore: Update GPD info and link

- lib/constant.dart
> feat: added status for Platform's Authorization configurator service

- lib/constant.dart
- Add receipt generator to status page
Show receipt generator function info on status page
> [PRDP-127] feat: Add receipt generator to status page

- lib/constant.dart
- lib/pages/home_page.dart
- lib/utils.dart
- macos/Runner.xcodeproj/project.pbxproj
- macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- pubspec.lock
- pubspec.yaml
* add "Last Updated" global label with button to refresh data
> feat(home): add "Last Updated" global label with button to refresh data

- lib/constant.dart
> chore: receipts service temporary removal

- lib/constant.dart
This reverts [commit fb7fcfafc03df2ea5aa9c576502550790b877f36](https://github.com/pagopa/pagopa-status-page/pull/13).
Reverted temporary removal
> revert: "chore: receipts service temporary removal"

- lib/constant.dart
- updated constant.dart with receipt helpdesk
> [PRDP-244] chore: update constant list with receipt helpdesk

- lib/components/fe_cell.dart
- lib/constant.dart
Depends on [this PR](https://github.com/pagopa/pagopa-selfcare-frontend/pull/291).
> feat: added version info retrieving for selfcare BO frontend

- lib/constant.dart
- added backoffice external service to status page
> [VAS-824] feat: Add backoffice external to status page

- lib/constant.dart
> feat(constant.dart): Update authorizer config

- lib/constant.dart
Add following products:
- `wispconverter`
- `wispsoapconverter`
- `wispconverterts` (technical support)
Local testing via 
`flutter run -d chrome --web-browser-flag "--disable-web-security" --web-port=8888`
> feat: Add WISP-Converter products [PAGOPA-1888]

- lib/constant.dart
- Introducing payments pull to status page config
https://pagopa.atlassian.net/browse/VAS-971
> [VAS-971] feat: add payments pull to constant for status page

- lib/constant.dart
- introducing print notice content to the status page
> [PPANTT-15] chore: add printit to status page constants

- lib/constant.dart
- fix repository name for generator
> fix: Printit configuration

- lib/constant.dart
- Add payment options to status page
[PPANTT#78](https://pagopa.atlassian.net/browse/PPANTT-78)
> [PPANTT-78] chore: Add payment options to status page

- lib/constant.dart
- added new eBollo services
[PPANTT-201](https://pagopa.atlassian.net/browse/PPANTT-201)
[PPANTT-201]: https://pagopa.atlassian.net/browse/PPANTT-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPANTT-201] feat: Configured status page for ebollo

- lib/constant.dart
> fix: ebollo status page

- lib/constant.dart
> fix: status page

- lib/constant.dart
> feat: [PAGOPA-2682] Adding FdR-related applications status

- .github/workflows/deploy-gh-pages.yml
> fix: refactoring pipeline in different jobs

- lib/bloc/versions/app_cubit.dart
- lib/constant.dart
- lib/pages/home_page.dart
- lib/pages/status_page.dart
- added RTP service to the status page
- added Anonymizer service to the status page
- removed `Nodo5` and `VAS`  tab
- added `Touchpoint` tab
- added projects sorting
[PAGOPA-3166](https://pagopa.atlassian.net/browse/PAGOPA-3166)
[PAGOPA-3166]: https://pagopa.atlassian.net/browse/PAGOPA-3166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [PAGOPA-3166]: Add RTP to status page
